### ISSUE TITLE
Misattribution of reviews, and not all reviews are found

### ISSUE THREAD

**Issue by Vempele** [fasiha/fuzzy-anki#1]
JOIN notes ON revlog.cid=notes.id 

This is wrong: revlog.cid is a card id, not a note id.

**Comment by fasiha** [comment]
@Vempele you're spot on. I was misled into comparing `revlog.cid` with `notes.id` because on my sole deck, the card ID and the note ID (almost) always match. I'm changing the SQL query to
`FROM revlog JOIN cards ON revlog.cid=cards.id JOIN notes ON cards.nid=notes.id`. Now, on my personal collection, I find all my reviews now.

I tried using the collection you shared on Dropbox and confused myself regarding the numbers you cited. In that file, md5hash 9c50e6903437c8b0ef87342b70abdb30, I see three reviews and two cards and two notes using just an sqlite3 browser. But previously the app was finding only two of three reviews and showing the wrong notes for those reviews, and now I believe it's better. Can you check with your test/full database now?

**Comment by fasiha** [comment]
(Accidentally deleted the previous comment...)

Now, by using outer (instead of inner) join in the SQL query, I'm capturing reviews of deleted cards/notes (and hopefully deleted models too, but I haven't tested that). The exported CSV should contain "unknown..." for the unavailable fields.

Please try it with your test/full databases!

**Comment by Vempele** [comment]
131751 reviews found, 1074 instances of "unknown deck" in the file. Matches what I see in Anki now!

**Comment by fasiha** [comment]
That's a close---thank you!!!
